In [4]:
import os
os.getcwd()

'c:\\Users\\Admin\\Desktop\\Crop-Yield-Prediction\\datasets\\notebooks'

In [5]:
import os

print(os.listdir("../raw"))

['Crop_recommendation.csv', 'FAOSTAT_data_en_7-26-2026.csv', 'pesticides.csv', 'rainfall.csv', 'state_soil_data.csv', 'state_weather_data_1997_2020.csv', 'temp.csv', 'yield.csv', 'yield_df.csv']

In [2]:
import pandas as pd
import numpy as np

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [7]:
import pandas as pd

crop = pd.read_csv("../raw/Crop_recommendation.csv")
yield_data = pd.read_csv("../raw/yield.csv")
yield_df = pd.read_csv("../raw/yield_df.csv")
weather = pd.read_csv("../raw/state_weather_data_1997_2020.csv")
soil = pd.read_csv("../raw/state_soil_data.csv")
rainfall = pd.read_csv("../raw/rainfall.csv")
temperature = pd.read_csv("../raw/temp.csv")
pesticides = pd.read_csv("../raw/pesticides.csv")
fao = pd.read_csv("../raw/FAOSTAT_data_en_7-26-2026.csv")

In [8]:
datasets = {
    "Crop Recommendation": crop,
    "Yield": yield_data,
    "Yield DF": yield_df,
    "Weather": weather,
    "Soil": soil,
    "Rainfall": rainfall,
    "Temperature": temperature,
    "Pesticides": pesticides,
    "FAOSTAT": fao
}

for name, df in datasets.items():
    print("="*50)
    print(name)
    print(df.shape)
    print(df.head(3))

==================================================
Crop Recommendation
(2200, 8)
    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
==================================================
Yield
(56717, 12)
  Domain Code Domain  Area Code         Area  Element Code Element  Item Code  \
0          QC  Crops          2  Afghanistan          5419   Yield         56
1          QC  Crops          2  Afghanistan          5419   Yield         56
2          QC  Crops          2  Afghanistan          5419   Yield         56

    Item  Year Code  Year   Unit  Value
0  Maize       1961  1961  hg/ha  14000
1  Maize       1962  1962  hg/ha  14000
2  Maize       1963  1963  hg/ha  14260
==================================================
Yield DF
(28242, 8)
   Unnamed: 0     Area         Item  Year  hg/ha_yield  \
0           0  Albania        Maize  1990        36613
1           1  Albania     Potatoes  1990        66667
2           2  Albania  Rice, paddy  1990        23333

   average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp
0                         1485.0              121.0     16.37
1                         1485.0              121.0     16.37
2                         1485.0              121.0     16.37
==================================================
Weather
(720, 5)
            state  year  avg_temp_c  total_rainfall_mm  avg_humidity_percent
0  Andhra Pradesh  1997       28.21            1191.08                 69.56
1  Andhra Pradesh  1998       28.21            1100.41                 71.95
2  Andhra Pradesh  1999       28.03             603.67                 66.91
==================================================
Soil
(30, 5)
               state   N   P   K   pH
0     Andhra Pradesh  78  45  22  6.8
1  Arunachal Pradesh  55  15  35  5.5
2              Assam  60  18  38  5.8
==================================================
Rainfall
(6727, 3)
          Area  Year average_rain_fall_mm_per_year
0  Afghanistan  1985                           327
1  Afghanistan  1986                           327
2  Afghanistan  1987                           327
==================================================
Temperature
(71311, 3)
   year        country  avg_temp
0  1849  Côte D'Ivoire     25.58
1  1850  Côte D'Ivoire     25.52
2  1851  Côte D'Ivoire     25.67
==================================================
Pesticides
(4349, 7)
           Domain     Area Element                Item  Year  \
0  Pesticides Use  Albania     Use  Pesticides (total)  1990
1  Pesticides Use  Albania     Use  Pesticides (total)  1991
2  Pesticides Use  Albania     Use  Pesticides (total)  1992

                           Unit  Value
0  tonnes of active ingredients  121.0
1  tonnes of active ingredients  121.0
2  tonnes of active ingredients  121.0
==================================================
FAOSTAT
(15622, 15)
  Domain Code                        Domain  Area Code (M49)   Area  \
0         QCL  Crops and livestock products              356  India
1         QCL  Crops and livestock products              356  India
2         QCL  Crops and livestock products              356  India

   Element Code         Element  Item Code (CPC)               Item  \
0          5312  Area harvested           1371.0  Almonds, in shell
1          5510      Production           1371.0  Almonds, in shell
2          5312  Area harvested           1371.0  Almonds, in shell

   Year Code  Year Unit    Value Flag                  Flag Description Note
0       2010  2010   ha      NaN    M  Missing value; data cannot exist  NaN
1       2010  2010    t      NaN    M  Missing value; data cannot exist  NaN
2       2011  2011   ha  23000.0    A                    Official value  NaN

In [9]:
for name, df in datasets.items():
    print("="*60)
    print(name)
    df.info()

============================================================
Crop Recommendation
<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   str
dtypes: float64(4), int64(3), str(1)
memory usage: 137.6 KB
============================================================
Yield
<class 'pandas.DataFrame'>
RangeIndex: 56717 entries, 0 to 56716
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Domain Code   56717 non-null  str
 1   Domain        56717 non-null  str
 2   Area Code     56717 non-null  int64
 3   Area          56717 non-null  str
 4   Element Code  56717 non-null  int64
 5   Element       56717 non-null  str
 6   Item Code     56717 non-null  int64
 7   Item          56717 non-null  str
 8   Year Code     56717 non-null  int64
 9   Year          56717 non-null  int64
 10  Unit          56717 non-null  str
 11  Value         56717 non-null  int64
dtypes: int64(6), str(6)
memory usage: 5.2 MB
============================================================
Yield DF
<class 'pandas.DataFrame'>
RangeIndex: 28242 entries, 0 to 28241
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     28242 non-null  int64
 1   Area                           28242 non-null  str
 2   Item                           28242 non-null  str
 3   Year                           28242 non-null  int64
 4   hg/ha_yield                    28242 non-null  int64
 5   average_rain_fall_mm_per_year  28242 non-null  float64
 6   pesticides_tonnes              28242 non-null  float64
 7   avg_temp                       28242 non-null  float64
dtypes: float64(3), int64(3), str(2)
memory usage: 1.7 MB
============================================================
Weather
<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   state                 720 non-null    str
 1   year                  720 non-null    int64
 2   avg_temp_c            720 non-null    float64
 3   total_rainfall_mm     720 non-null    float64
 4   avg_humidity_percent  720 non-null    float64
dtypes: float64(3), int64(1), str(1)
memory usage: 28.3 KB
============================================================
Soil
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   state   30 non-null     str
 1   N       30 non-null     int64
 2   P       30 non-null     int64
 3   K       30 non-null     int64
 4   pH      30 non-null     float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.3 KB
============================================================
Rainfall
<class 'pandas.DataFrame'>
RangeIndex: 6727 entries, 0 to 6726
Data columns (total 3 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0    Area                          6727 non-null   str
 1   Year                           6727 non-null   int64
 2   average_rain_fall_mm_per_year  5953 non-null   str
dtypes: int64(1), str(2)
memory usage: 157.8 KB
============================================================
Temperature
<class 'pandas.DataFrame'>
RangeIndex: 71311 entries, 0 to 71310
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   year      71311 non-null  int64
 1   country   71311 non-null  str
 2   avg_temp  68764 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.6 MB
============================================================
Pesticides
<class 'pandas.DataFrame'>
RangeIndex: 4349 entries, 0 to 4348
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Domain   4349 non-null   str
 1   Area     4349 non-null   str
 2   Element  4349 non-null   str
 3   Item     4349 non-null   str
 4   Year     4349 non-null   int64
 5   Unit     4349 non-null   str
 6   Value    4349 non-null   float64
dtypes: float64(1), int64(1), str(5)
memory usage: 238.0 KB
============================================================
FAOSTAT
<class 'pandas.DataFrame'>
RangeIndex: 15622 entries, 0 to 15621
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       15622 non-null  str
 1   Domain            15622 non-null  str
 2   Area Code (M49)   15622 non-null  int64
 3   Area              15622 non-null  str
 4   Element Code      15622 non-null  int64
 5   Element           15622 non-null  str
 6   Item Code (CPC)   15622 non-null  float64
 7   Item              15622 non-null  str
 8   Year Code         15622 non-null  int64
 9   Year              15622 non-null  int64
 10  Unit              15622 non-null  str
 11  Value             15490 non-null  float64
 12  Flag              15622 non-null  str
 13  Flag Description  15622 non-null  str
 14  Note              458 non-null    str
dtypes: float64(2), int64(4), str(9)
memory usage: 1.8 MB

In [10]:
for name, df in datasets.items():
    print("="*60)
    print(name)
    print(df.isnull().sum())

============================================================
Crop Recommendation
N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64
============================================================
Yield
Domain Code     0
Domain          0
Area Code       0
Area            0
Element Code    0
Element         0
Item Code       0
Item            0
Year Code       0
Year            0
Unit            0
Value           0
dtype: int64
============================================================
Yield DF
Unnamed: 0                       0
Area                             0
Item                             0
Year                             0
hg/ha_yield                      0
average_rain_fall_mm_per_year    0
pesticides_tonnes                0
avg_temp                         0
dtype: int64
============================================================
Weather
state                   0
year                    0
avg_temp_c              0
total_rainfall_mm       0
avg_humidity_percent    0
dtype: int64
============================================================
Soil
state    0
N        0
P        0
K        0
pH       0
dtype: int64
============================================================
Rainfall
 Area                              0
Year                               0
average_rain_fall_mm_per_year    774
dtype: int64
============================================================
Temperature
year           0
country        0
avg_temp    2547
dtype: int64
============================================================
Pesticides
Domain     0
Area       0
Element    0
Item       0
Year       0
Unit       0
Value      0
dtype: int64
============================================================
FAOSTAT
Domain Code             0
Domain                  0
Area Code (M49)         0
Area                    0
Element Code            0
Element                 0
Item Code (CPC)         0
Item                    0
Year Code               0
Year                    0
Unit                    0
Value                 132
Flag                    0
Flag Description        0
Note                15164
dtype: int64

In [11]:
for name, df in datasets.items():
    print("="*60)
    print(name)
    print("Duplicates:", df.duplicated().sum())

============================================================
Crop Recommendation
Duplicates: 0
============================================================
Yield
Duplicates: 0
============================================================
Yield DF
Duplicates: 0
============================================================
Weather
Duplicates: 0
============================================================
Soil
Duplicates: 0
============================================================
Rainfall
Duplicates: 0
============================================================
Temperature
Duplicates: 6958
============================================================
Pesticides
Duplicates: 0
============================================================
FAOSTAT
Duplicates: 0

In [16]:
temperature.head()
temperature.info()
temperature.columns.tolist()
temperature[temperature.duplicated()].head(20)

<class 'pandas.DataFrame'>
RangeIndex: 71311 entries, 0 to 71310
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   year      71311 non-null  int64
 1   country   71311 non-null  str
 2   avg_temp  68764 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.6 MB

      year        country  avg_temp
1285  1808          India       NaN
1286  1809          India       NaN
1287  1810          India       NaN
1288  1811          India       NaN
1289  1812          India       NaN
1335  1858          India       NaN
1336  1859          India       NaN
1337  1860          India       NaN
1338  1861          India       NaN
1339  1862          India       NaN
1340  1863          India       NaN
1341  1864          India       NaN
2143  1978  United States     11.56
2452  1808          India       NaN
2453  1809          India       NaN
2454  1810          India       NaN
2455  1811          India       NaN
2456  1812          India       NaN
2506  1862          India       NaN
2507  1863          India       NaN

In [17]:
for name, df in datasets.items():
    print("=" * 60)
    print(name)
    print(df.isnull().sum())

============================================================
Crop Recommendation
N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64
============================================================
Yield
Domain Code     0
Domain          0
Area Code       0
Area            0
Element Code    0
Element         0
Item Code       0
Item            0
Year Code       0
Year            0
Unit            0
Value           0
dtype: int64
============================================================
Yield DF
Unnamed: 0                       0
Area                             0
Item                             0
Year                             0
hg/ha_yield                      0
average_rain_fall_mm_per_year    0
pesticides_tonnes                0
avg_temp                         0
dtype: int64
============================================================
Weather
state                   0
year                    0
avg_temp_c              0
total_rainfall_mm       0
avg_humidity_percent    0
dtype: int64
============================================================
Soil
state    0
N        0
P        0
K        0
pH       0
dtype: int64
============================================================
Rainfall
 Area                              0
Year                               0
average_rain_fall_mm_per_year    774
dtype: int64
============================================================
Temperature
year           0
country        0
avg_temp    2547
dtype: int64
============================================================
Pesticides
Domain     0
Area       0
Element    0
Item       0
Year       0
Unit       0
Value      0
dtype: int64
============================================================
FAOSTAT
Domain Code             0
Domain                  0
Area Code (M49)         0
Area                    0
Element Code            0
Element                 0
Item Code (CPC)         0
Item                    0
Year Code               0
Year                    0
Unit                    0
Value                 132
Flag                    0
Flag Description        0
Note                15164
dtype: int64

In [18]:
rainfall[rainfall.isnull().any(axis=1)]

                       Area  Year average_rain_fall_mm_per_year
93           American Samoa  1985                           NaN
94           American Samoa  1986                           NaN
95           American Samoa  1987                           NaN
96           American Samoa  1989                           NaN
97           American Samoa  1990                           NaN
...                     ...   ...                           ...
6598  Virgin Islands (U.S.)  2013                           NaN
6599  Virgin Islands (U.S.)  2014                           NaN
6600  Virgin Islands (U.S.)  2015                           NaN
6601  Virgin Islands (U.S.)  2016                           NaN
6602  Virgin Islands (U.S.)  2017                           NaN

[774 rows x 3 columns]

In [19]:
import os
os.makedirs("../processed", exist_ok=True)

In [22]:
yield_df.columns

Index(['Area', 'Item', 'Year', 'hg/ha_yield', 'average_rain_fall_mm_per_year',
       'pesticides_tonnes', 'avg_temp'],
      dtype='str')

In [23]:
if "Unnamed: 0" in yield_df.columns:
    yield_df.drop(columns=["Unnamed: 0"], inplace=True)
rainfall["average_rain_fall_mm_per_year"] = rainfall["average_rain_fall_mm_per_year"].fillna(
    rainfall["average_rain_fall_mm_per_year"].median()
)

TypeError: Cannot perform reduction 'median' with string dtype

In [25]:
#Rainfall
rainfall.info()
rainfall["average_rain_fall_mm_per_year"] = pd.to_numeric(
    rainfall["average_rain_fall_mm_per_year"],
    errors="coerce"
)
rainfall["average_rain_fall_mm_per_year"].fillna(
    rainfall["average_rain_fall_mm_per_year"].median(),
    inplace=True
)

<class 'pandas.DataFrame'>
RangeIndex: 6727 entries, 0 to 6726
Data columns (total 3 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0    Area                          6727 non-null   str
 1   Year                           6727 non-null   int64
 2   average_rain_fall_mm_per_year  5947 non-null   float64
dtypes: float64(1), int64(1), str(1)
memory usage: 157.8 KB

C:\Users\Admin\AppData\Local\Temp\ipykernel_30804\2846219707.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  rainfall["average_rain_fall_mm_per_year"].fillna(

0       327.0
1       327.0
2       327.0
3       327.0
4       327.0
        ...
6722    657.0
6723    657.0
6724    657.0
6725    657.0
6726    657.0
Name: average_rain_fall_mm_per_year, Length: 6727, dtype: float64

In [26]:
if "Unnamed: 0" in yield_df.columns:
    yield_df.drop(columns=["Unnamed:0"], inplace=True, errors="ignore")

In [28]:
#temp
temperature.isnull().sum()
temperature["avg_temp"] = temperature["avg_temp"].fillna(
    temperature["avg_temp"].mean()
)

In [29]:
fao.drop(columns=["Note"], inplace=True)
fao["Value"] = fao["Value"].fillna(fao["Value"].median())

In [30]:
crop.to_csv("../processed/crop_recommendation_clean.csv", index=False)

weather.to_csv("../processed/weather_clean.csv", index=False)

soil.to_csv("../processed/soil_clean.csv", index=False)

yield_df.to_csv("../processed/yield_df_clean.csv", index=False)

yield_data.to_csv("../processed/yield_clean.csv", index=False)

rainfall.to_csv("../processed/rainfall_clean.csv", index=False)

temperature.to_csv("../processed/temperature_clean.csv", index=False)

pesticides.to_csv("../processed/pesticides_clean.csv", index=False)

fao.to_csv("../processed/faostat_clean.csv", index=False)

In [37]:
for name, df in {
    "Crop": crop,
    "Weather": weather,
    "Soil": soil,
    "Yield": yield_data,
    "Yield DF": yield_df,
    "Rainfall": rainfall,
    "Temperature": temperature,
    "Pesticides": pesticides,
    "FAOSTAT": fao
}.items():
    print("=" * 40)
    print(name)
    print(df.isnull().sum().sum())

========================================
Crop
0
========================================
Weather
0
========================================
Soil
0
========================================
Yield
0
========================================
Yield DF
0
========================================
Rainfall
0
========================================
Temperature
0
========================================
Pesticides
0
========================================
FAOSTAT
0

In [32]:
rainfall.info()

<class 'pandas.DataFrame'>
RangeIndex: 6727 entries, 0 to 6726
Data columns (total 3 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0    Area                          6727 non-null   str
 1   Year                           6727 non-null   int64
 2   average_rain_fall_mm_per_year  5947 non-null   float64
dtypes: float64(1), int64(1), str(1)
memory usage: 157.8 KB

In [33]:
rainfall["average_rain_fall_mm_per_year"].isnull().sum()

np.int64(780)

In [35]:
median_value = rainfall["average_rain_fall_mm_per_year"].median()

rainfall["average_rain_fall_mm_per_year"] = rainfall["average_rain_fall_mm_per_year"].fillna(median_value)
rainfall["average_rain_fall_mm_per_year"].isnull().sum()

np.int64(0)

In [36]:
temperature.isnull().sum()

year        0
country     0
avg_temp    0
dtype: int64

In [38]:
crop.to_csv("../processed/crop_recommendation_clean.csv", index=False)

yield_df.to_csv("../processed/yield_df_clean.csv", index=False)

weather.to_csv("../processed/weather_clean.csv", index=False)

soil.to_csv("../processed/soil_clean.csv", index=False)

rainfall.to_csv("../processed/rainfall_clean.csv", index=False)

temperature.to_csv("../processed/temperature_clean.csv", index=False)

pesticides.to_csv("../processed/pesticides_clean.csv", index=False)

fao.to_csv("../processed/faostat_clean.csv", index=False)