In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
yield_df = pd.read_csv("yield.csv")
print(yield_df.shape)

(56717, 12)

In [3]:
yield_df_processed = pd.read_csv("yield_df.csv")
print("yield_df.csv", yield_df_processed.shape)

yield_df.csv (28242, 8)

In [4]:
print("yield.csv colums")
print(yield_df.columns.tolist())

print("\n")

print("yield_df.csv columns")
print(yield_df_processed.columns.tolist())

yield.csv colums
['Domain Code', 'Domain', 'Area Code', 'Area', 'Element Code', 'Element', 'Item Code', 'Item', 'Year Code', 'Year', 'Unit', 'Value']


yield_df.csv columns
['Unnamed: 0', 'Area', 'Item', 'Year', 'hg/ha_yield', 'average_rain_fall_mm_per_year', 'pesticides_tonnes', 'avg_temp']

In [5]:
yield_df.head()

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value
0,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1961,1961,hg/ha,14000
1,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1962,1962,hg/ha,14000
2,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1963,1963,hg/ha,14260
3,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1964,1964,hg/ha,14257
4,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1965,1965,hg/ha,14400

In [6]:
yield_df_processed.head()

,Unnamed: 0,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,0,Albania,Maize,1990,36613,1485.0,121.0,16.37
1,1,Albania,Potatoes,1990,66667,1485.0,121.0,16.37
2,2,Albania,"Rice, paddy",1990,23333,1485.0,121.0,16.37
3,3,Albania,Sorghum,1990,12500,1485.0,121.0,16.37
4,4,Albania,Soybeans,1990,7000,1485.0,121.0,16.37

In [7]:
temperature_df = pd.read_csv("temp.csv")
print(temperature_df.shape)

(71311, 3)

In [8]:
rainfall_df = pd.read_csv("rainfall.csv")
print(rainfall_df.shape)

(6727, 3)

In [9]:
pesticides_df = pd.read_csv("pesticides.csv")
print(pesticides_df.shape)

(4349, 7)

In [10]:
print(temperature_df.columns.tolist())

['year', 'country', 'avg_temp']

In [11]:
print(rainfall_df.columns.tolist())

[' Area', 'Year', 'average_rain_fall_mm_per_year']

In [12]:
print(pesticides_df.columns.tolist())

['Domain', 'Area', 'Element', 'Item', 'Year', 'Unit', 'Value']

In [13]:
print(temperature_df.head())

   year        country  avg_temp
0  1849  Côte D'Ivoire     25.58
1  1850  Côte D'Ivoire     25.52
2  1851  Côte D'Ivoire     25.67
3  1852  Côte D'Ivoire       NaN
4  1853  Côte D'Ivoire       NaN

In [14]:
print(rainfall_df.head())

          Area  Year average_rain_fall_mm_per_year
0  Afghanistan  1985                           327
1  Afghanistan  1986                           327
2  Afghanistan  1987                           327
3  Afghanistan  1989                           327
4  Afghanistan  1990                           327

In [15]:
print(pesticides_df.head())

           Domain     Area Element                Item  Year  \
0  Pesticides Use  Albania     Use  Pesticides (total)  1990
1  Pesticides Use  Albania     Use  Pesticides (total)  1991
2  Pesticides Use  Albania     Use  Pesticides (total)  1992
3  Pesticides Use  Albania     Use  Pesticides (total)  1993
4  Pesticides Use  Albania     Use  Pesticides (total)  1994

                           Unit  Value
0  tonnes of active ingredients  121.0
1  tonnes of active ingredients  121.0
2  tonnes of active ingredients  121.0
3  tonnes of active ingredients  121.0
4  tonnes of active ingredients  201.0

In [20]:
faostat_df = pd.read_csv("faostat_crop_production.csv")
faostat_df.shape

(6074, 15)

In [21]:
print(faostat_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6074 entries, 0 to 6073
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       6074 non-null   object
 1   Domain            6074 non-null   object
 2   Area Code (M49)   6074 non-null   int64
 3   Area              6074 non-null   object
 4   Element Code      6074 non-null   int64
 5   Element           6074 non-null   object
 6   Item Code (CPC)   6074 non-null   float64
 7   Item              6074 non-null   object
 8   Year Code         6074 non-null   int64
 9   Year              6074 non-null   int64
 10  Unit              6074 non-null   object
 11  Value             6074 non-null   float64
 12  Flag              6074 non-null   object
 13  Flag Description  6074 non-null   object
 14  Note              0 non-null      float64
dtypes: float64(3), int64(4), object(8)
memory usage: 711.9+ KB
None

In [22]:
faostat_df.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,QCL,Crops and livestock products,356,India,5412,Yield,1371.0,"Almonds, in shell",2011,2011,kg/ha,608.7,A,Official value,NaN
1,QCL,Crops and livestock products,356,India,5412,Yield,1371.0,"Almonds, in shell",2012,2012,kg/ha,181.8,A,Official value,NaN
2,QCL,Crops and livestock products,356,India,5412,Yield,1371.0,"Almonds, in shell",2013,2013,kg/ha,428.6,A,Official value,NaN
3,QCL,Crops and livestock products,356,India,5412,Yield,1371.0,"Almonds, in shell",2014,2014,kg/ha,619.0,A,Official value,NaN
4,QCL,Crops and livestock products,356,India,5412,Yield,1371.0,"Almonds, in shell",2015,2015,kg/ha,476.2,A,Official value,NaN

In [26]:
usda_df = pd.read_csv("usda_crop_yield.csv")
usda_df.shape

C:\Users\Admin\AppData\Local\Temp\ipykernel_8896\1903702029.py:1: DtypeWarning: Columns (0,31) have mixed types. Specify dtype option on import or set low_memory=False.
  usda_df = pd.read_csv("usda_crop_yield.csv")

(98937, 39)

In [28]:
usda_df.columns.tolist()

['region_desc',
 'load_time',
 'asd_code',
 'year',
 'sector_desc',
 'week_ending',
 'asd_desc',
 'country_code',
 'domaincat_desc',
 'congr_district_code',
 'county_name',
 'state_alpha',
 'group_desc',
 'end_code',
 'domain_desc',
 'county_ansi',
 'statisticcat_desc',
 'state_fips_code',
 'CV (%)',
 'county_code',
 'class_desc',
 'prodn_practice_desc',
 'reference_period_desc',
 'zip_5',
 'source_desc',
 'location_desc',
 'util_practice_desc',
 'agg_level_desc',
 'short_desc',
 'unit_desc',
 'commodity_desc',
 'Value',
 'country_name',
 'watershed_code',
 'begin_code',
 'watershed_desc',
 'state_name',
 'state_ansi',
 'freq_desc']

In [29]:
usda_df.head()

,region_desc,load_time,asd_code,year,sector_desc,week_ending,asd_desc,country_code,domaincat_desc,congr_district_code,...,unit_desc,commodity_desc,Value,country_name,watershed_code,begin_code,watershed_desc,state_name,state_ansi,freq_desc
0,NaN,2024-02-23 15:00:00.000,10.0,2019,CROPS,NaN,NORTHERN VALLEY,9000,NOT SPECIFIED,NaN,...,BU / ACRE,CORN,166.5,UNITED STATES,0,0,NaN,ALABAMA,1.0,ANNUAL
1,NaN,2024-02-23 15:00:00.000,10.0,2018,CROPS,NaN,NORTHERN VALLEY,9000,NOT SPECIFIED,NaN,...,BU / ACRE,CORN,166.5,UNITED STATES,0,0,NaN,ALABAMA,1.0,ANNUAL
2,NaN,2018-02-22 15:08:35.000,10.0,2017,CROPS,NaN,NORTHERN VALLEY,9000,NOT SPECIFIED,NaN,...,BU / ACRE,CORN,189.4,UNITED STATES,0,0,NaN,ALABAMA,1.0,ANNUAL
3,NaN,2017-02-23 15:00:08.000,10.0,2016,CROPS,NaN,NORTHERN VALLEY,9000,NOT SPECIFIED,NaN,...,BU / ACRE,CORN,123.0,UNITED STATES,0,0,NaN,ALABAMA,1.0,ANNUAL
4,NaN,2016-02-18 15:04:50.000,10.0,2015,CROPS,NaN,NORTHERN VALLEY,9000,NOT SPECIFIED,NaN,...,BU / ACRE,CORN,159.0,UNITED STATES,0,0,NaN,ALABAMA,1.0,ANNUAL

In [31]:
yield_df_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28242 entries, 0 to 28241
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     28242 non-null  int64
 1   Area                           28242 non-null  object
 2   Item                           28242 non-null  object
 3   Year                           28242 non-null  int64
 4   hg/ha_yield                    28242 non-null  int64
 5   average_rain_fall_mm_per_year  28242 non-null  float64
 6   pesticides_tonnes              28242 non-null  float64
 7   avg_temp                       28242 non-null  float64
dtypes: float64(3), int64(3), object(2)
memory usage: 1.7+ MB

In [32]:
yield_df_processed.describe()

,Unnamed: 0,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
count,28242.000000,28242.000000,28242.000000,28242.00000,28242.000000,28242.000000
mean,14120.500000,2001.544296,77053.332094,1149.05598,37076.909344,20.542627
std,8152.907488,7.051905,84956.612897,709.81215,59958.784665,6.312051
min,0.000000,1990.000000,50.000000,51.00000,0.040000,1.300000
25%,7060.250000,1995.000000,19919.250000,593.00000,1702.000000,16.702500
50%,14120.500000,2001.000000,38295.000000,1083.00000,17529.440000,21.510000
75%,21180.750000,2008.000000,104676.750000,1668.00000,48687.880000,26.000000
max,28241.000000,2013.000000,501412.000000,3240.00000,367778.000000,30.650000

In [33]:
yield_df_processed.isnull().sum()

Unnamed: 0                       0
Area                             0
Item                             0
Year                             0
hg/ha_yield                      0
average_rain_fall_mm_per_year    0
pesticides_tonnes                0
avg_temp                         0
dtype: int64